L2 refactor
contentauth/c2pa-js-legacy pull request #135
Opened 2024-02-06 23:52 UTC by MassivaM

## Changes in this pull request
Refactor with the new "nutritional fact" style, added the web3 , content summary and AI tool used sections

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] All applicable changes have been documented
- [ ] Any `TO DO` items (or similar) have been entered as GitHub issues and the link to that issue has been included in a comment

2024-02-06 23:54 UTC, MassivaM commented on packages/c2pa-wc/src/components/PanelSection/PanelSection.ts
> +          &nbsp;
is there a better way to add a space between the header and content?

2024-02-06 23:56 UTC, MassivaM commented
@dkozma it looks like my changes from c2pa aren't being brought in, does it have to be a separate PR?

2024-02-13 15:40 UTC, MassivaM commented on packages/toolkit/types/index.ts
> +  | Web3Assertion;
I'm not sure if web3 should be part of ManifestAssertion here or be an extended assertion in `createL2ManifestStore`

2024-02-13 20:12 UTC, MassivaM commented on packages/c2pa-wc/src/components/PanelSection/PanelSection.ts
> +          &nbsp;
The `&nbsp` also created problems whenever a section doesn't have a header slot because it still shows and takes up space 
<img width="252" alt="image" src="https://github.com/contentauth/c2pa-js/assets/35381715/2a993b3d-33e3-4228-b24a-d2b1c3492cd8">

2024-02-13 20:21 UTC, MassivaM commented on packages/c2pa-wc/src/components/ManifestSummary/ManifestSummary.ts
> +        #content-container > *:not([empty]):not(:last-child:empty),
this `:not(:last-child)` doesnt seem to work because id like for the last section not to have a bottom border since the container's border handles that 
<img width="349" alt="image" src="https://github.com/contentauth/c2pa-js/assets/35381715/e1dc5f27-552b-444d-9077-17b4f68e3dcb">

2024-02-15 03:39 UTC, dkozma requested changes
Looking good! Some changes requested.

2024-02-15 03:39 UTC, dkozma commented on packages/c2pa-wc/src/components/AIToolUsed/AIToolUsed.ts
> +}
I feel like I've seen this code before - can we add it to the SDK if we use it in multiple places?

2024-02-15 03:39 UTC, dkozma commented on packages/c2pa-wc/src/components/ContentSummary/ContentSummary.ts
> +
Same with this function - if we use it in multiple places, let's consolidate it into the JS SDK. Also please remove the `console.log`.

2024-02-15 03:39 UTC, dkozma commented on packages/c2pa-wc/src/components/PanelSection/PanelSection.ts
> +          &nbsp;
I'm wondering if you can do something like:
```css
.heading-text ::slotted(*) {
    margin-bottom: 10px; /* or whatever */
}
```

2024-02-15 03:39 UTC, dkozma commented on packages/c2pa-wc/src/components/SocialMedia/SocialMedia.ts
> +          gap: 1 px;
```suggestion
          gap: 1px;
```

2024-02-15 03:39 UTC, dkozma commented on packages/c2pa-wc/src/components/SocialMedia/SocialMedia.ts
> +          padding-left: 10 px;
```suggestion
          padding-left: 10px;
```

2024-02-15 03:39 UTC, dkozma commented on packages/c2pa-wc/src/components/Web3/Web3.ts
> +        }
```suggestion
        .web3-list {
          display: flex;
          flex-direction: column;
          gap: 7px;
          list-style: none;
          padding: 0;
          margin: 0;
          overflow: hidden;
        }
```

2024-02-15 03:39 UTC, dkozma commented on packages/c2pa-wc/src/components/Web3/Web3.ts
> +        }
Is this needed? It looks like this is defined in the Web3Pill component below.

2024-02-15 03:39 UTC, dkozma commented on packages/c2pa-wc/src/components/Web3/Web3Pill.ts
> +          background-color: #e5e5e5;
Should this use `--cai-background-pill`?

2024-02-15 03:39 UTC, dkozma commented on packages/c2pa-wc/storybook/fixtures/manifest.ts
> +    name: 'Gavin Peacock asbadbhsavdhsavdhjadjavjdash',
Do we want this text as the default?

2024-02-15 03:39 UTC, dkozma commented on packages/toolkit/types/index.ts
> +  | Web3Assertion;
@emensch might have a better idea about that.

2024-02-15 20:50 UTC, MassivaM commented on packages/c2pa-wc/src/components/AIToolUsed/AIToolUsed.ts
> +}
ya it comes from Verify , once we push the new build I can update there too

2024-02-15 21:25 UTC, MassivaM commented on packages/c2pa-wc/src/components/ManifestSummary/ManifestSummary.ts
> +        #content-container > *:not([empty]):not(:last-child:empty),
@dkozma any idea on this?

2024-02-23 21:06 UTC, emensch commented on packages/toolkit/types/index.ts
> +  | Web3Assertion;
ah yes... interesting. @dkozma do you know what the latest is on web3 support? I don't feel great about including an `adobe` assertion in the open-source code, but if we need to show web3 as part of the open-source components I'm not sure what option we have?

2024-03-06 02:18 UTC, dkozma requested changes
I added some questions/small changes as well as a commit that removes the `pre` and `default` slots for `ManifestSummary` and fixes the border issue that you should review.

2024-03-06 02:18 UTC, dkozma commented on packages/c2pa-wc/src/components/ProducedWith/ProducedWith.ts
> +          <span> ${this._data?.product}    ${
Will this return `undefined` or an empty string if `this._data` doesn't exist? Do we need something like `${this._data?.product ?? ''}`?

2024-03-06 02:18 UTC, dkozma commented on packages/c2pa-wc/src/components/ProducedWith/ProducedWith.ts
> +      this.manifestStore?.isBeta
Same question here (also formatting looks a bit weird)

2024-03-06 02:18 UTC, dkozma commented on packages/c2pa-wc/src/components/Web3/Web3Pill.ts
> +        .web3-pill {
Should this have `cursor: pointer;` if it is clickable?

2024-03-06 02:18 UTC, dkozma commented on packages/c2pa-wc/src/components/Web3/Web3Pill.ts
> +    }, 800);
It would be nice to have `800` as a customizable prop.

2024-03-06 02:18 UTC, dkozma commented on packages/c2pa-wc/src/components/Web3/Web3Pill.ts
> +          ? html` <div class="web3-copied">Copied!</div> `
`Copied!` needs a translation tag.

2024-03-15 21:59 UTC, MassivaM commented on packages/c2pa-wc/src/components/Web3/Web3.ts
> +import { L2Web3 } from 'c2pa/dist/src/createL2ManifestStore';
@dkozma Since this type is new I wasn't able to bring in from 'c2pa' directly while developing , should I change it to 'c2ppa' since it will become an available type once we cut a release

2024-03-15 22:53 UTC, dkozma commented on packages/c2pa-wc/src/components/ManifestSummary/ManifestSummary.ts
> -              ${this._config?.sections?.contentSummary
Are the sections in the config still being used? If not, should we just take this out? cc @emensch

2024-03-18 17:16 UTC, dkozma commented on packages/c2pa-wc/src/components/ManifestSummary/ManifestSummary.ts
> +    console.log('viewMoreUrl', this.viewMoreUrl);
✂️

2024-03-18 17:17 UTC, dkozma approved these changes
@MassivaM Please just remove the `console.log` and we should be good to go.

2024-03-19 18:37 UTC, merged