added hidden box in indicator & trigger on element
contentauth/c2pa-js-legacy pull request #72
Opened 2023-01-19 17:34 UTC by MassivaM

## Changes in this pull request
This PR makes sure that the L2 manifest summary closes when the tooltip is exited without needing to enter the manifest-summary

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] All applicable changes have been documented
- [ ] Any `TO DO` items (or similar) have been entered as GitHub issues and the link to that issue has been included in a comment

2023-01-19 17:50 UTC, dkozma commented on packages/c2pa-wc/src/components/Indicator/Indicator.ts
> +          width: calc(var(--cai-popover-icon-width, 16px) + 10px);
Curious as to why this is using `width` instead of `size` (and defaults to `16px` instead of `24px`).

2023-01-20 17:27 UTC, dkozma approved these changes
Thanks @MassivaM, I'd also like @emensch 's eyes on this before we make a new release.

2023-01-20 17:45 UTC, emensch commented on packages/c2pa-wc/src/components/Indicator/Indicator.ts
> +      <div class="hidden-layer"></div>
I wonder if it makes more sense for the hidden layer to be part of the popover component and not the indicator? 

Right now it seems like this would result in an unexpectedly large hover area with the popover closed. Additionally, we're adding specific responsibilities to the Indicator component that couple it more tightly with the Popover, which may not be desirable for other consumers of the Indicator component.

2023-01-20 18:20 UTC, dkozma commented on packages/c2pa-wc/src/components/Indicator/Indicator.ts
> +      <div class="hidden-layer"></div>
This is a good point @emensch.

2023-01-20 18:20 UTC, MassivaM commented on packages/c2pa-wc/src/components/Indicator/Indicator.ts
> +      <div class="hidden-layer"></div>
I'll try it!

2023-01-26 16:55 UTC, dkozma requested changes
2 tiny changes

2023-01-26 16:55 UTC, dkozma commented on packages/c2pa-wc/src/components/Popover/Popover.ts
> +      console.log('show,hide', show, hide);
✂️

2023-01-26 16:55 UTC, dkozma commented on packages/c2pa-wc/src/components/Indicator/Indicator.ts
> +    return html`<cai-icon-info class="icon" /> `;
Please remove trailing space.
```suggestion
    return html`<cai-icon-info class="icon" />`;
```

2023-01-27 16:26 UTC, dkozma approved these changes

2023-01-27 18:57 UTC, merged